### PR TITLE
JCGS

### PR DESCRIPTION
**Pull request by cpsievert**
@tdhock @srvanderplas @caijun @kferris10 

This pull request will serve as a platform for revisions before submitting to [JCGS](http://www.tandfonline.com/toc/ucgs20/current).

The jcgs branch branches off from the infovis16 branch. Infovis16 which wasn't merged into master, so it will contain commits from that revision process, but I think that's fine.

### CODE REVIEW

**Comment by tdhock** [comment]
hey I'm back from vacation and willing to work on revising the paper with you

**Comment by caijun** [comment]
While proof reading, I have a idea about the following code snippet

```
scatterPlot <- scatterPlot + geom_text(
  data = WorldBank,
  aes(x = fertility.rate, y = life.expectancy,
      label = country,
      showSelected = country,
      showSelected2 = year,
      showSelected3 = region)
)
```

Is `showSelected` aesthetic able to take a vector of multiple variable strings as input, as follows

```
scatterPlot <- scatterPlot + geom_text(
  data = WorldBank,
  aes(x = fertility.rate, y = life.expectancy,
      label = country,
      showSelected = c('country', 'year', 'region'))
)
```
If it is, then the syntax would be much more concise and elegant.

**Comment by tdhock** [comment]
I completely agree with you Tony. actually Faizan is working on that in
this year's GSOC, but it does not yet work with the current animint code.

**Comment by caijun** [comment]
For the animation part, we may need to include the comparison between animint and [tweenr](https://github.com/thomasp85/tweenr).

Recently I have seen lots of animation examples produced by using tweenr package. For example, the animated bubble chart from the gapminder data (http://blog.revolutionanalytics.com/2017/05/tweenr.html). It's also based on ggplot2 and can create smooth animations.

**Comment by cpsievert** [comment]
@caijun it looks like your text editor removed the line breaks in to the animint.Rmd file in 6096a84,
which makes it hard to see where you made actual changes. 

I've fixed a few things (without merging your commit) and decided to open #10 which branches off this PR. Was there anything important that you changed in animint.Rmd that I should transfer over?

**Comment by cpsievert** [comment]
Closed in favor of #10

**Pull request closed without merging**
